routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
    // You can also use auth middleware to prevent unauthenticated users
    Route::get('/', 'DashboardController@index');

    Route::group((['prefix' => 'perisai-plus']), function () {
        Route::get('/', 'PerisaiPlusController@index')->name('admin.perisai-plus');
        Route::get('/get-perisai-plus', 'PerisaiPlusController@getPerisaiPlus')->name('admin.perisai-plus.datatables');
    });
    Route::group((['prefix' => 'hubungi-kami']), function () {
        Route::get('/', 'HubungiKamiController@index')->name('admin.hubungi-kami');
        Route::get('/get-hubungi-kami', 'HubungiKamiController@getHubungiKami')->name('admin.hubungi-kami.datatables');
    });

    Route::group((['prefix' => 'about']), function () {
        Route::get('/', 'AboutusController@index')->name('admin.about');
        Route::post('/store/{id}', 'AboutusController@store')->name('admin.about.store');
    });

    Route::group((['prefix' => 'terms']), function () {
        Route::get('/', 'TermsController@index')->name('admin.terms');
        Route::post('/store/{id}', 'TermsController@store')->name('admin.terms.store');
    });

    Route::resource('settings', 'SettingController')->names('admin.settings');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Library\Helpers\BnilifeApi;
use Illuminate\Support\Facades\Cookie;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend'], function () {
  Route::group(['prefix' => 'produk'], function () {
    Route::get('/{slug}', 'ProductController@single_category')->name('produk.single_category');
  });
  Route::group(['prefix' => 'plan'], function () {
    Route::get('/{slug}', 'ProductController@single_product')->name('produk.single_product');
  });
  Route::get('/register', 'RegisterController@index')->name('register-plan');
  Route::get('/perisai-plus', 'PerisaiController@index')->name('front.perisai_plus');
});

Auth::routes(['register' => false]);
Route::get('/404', 'ErrorController@notfound');
Route::get('/500', 'ErrorController@pageerror');
Route::get('/polish', 'PolishController@index');




// hanya untuk test
// Route::post('geturl', 'MidtransController@getUrlPayment');
// Route::get('midtrans', 'MidtransController@index');


Route::get('perisai', 'Api\PerisaiController@index')->name('perisai');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/service', 'HomeController@service')->name('service');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/register/success', 'HomeController@registerSuccess')->name('register-success');
// Route::get('/product', 'HomeController@product');
// Route::get('/packet', 'HomeController@packet');

Route::get('/contact', 'HomeController@contact')->name('contact');

// Route::get('/test-email', function () {
//   $detail = [
//     'view' => 'mail.registration-perisai-plus',
//     'subject' => 'Hello',
//     'title' => 'Title',
//     'body' => 'Test Body',
//   ];
//   SendEmail::dispatch('kurniarocki30@gmail.com', $detail);
// });

resources/views/admin/layouts/footer-script.blade.php
        <!-- JAVASCRIPT -->
        <script src="{{ URL::asset('libs/jquery/jquery.min.js')}}"></script>
        <script src="{{ URL::asset('libs/bootstrap/bootstrap.min.js')}}"></script>
        <script src="{{ URL::asset('libs/metismenu/metismenu.min.js')}}"></script>
        <script src="{{ URL::asset('libs/simplebar/simplebar.min.js')}}"></script>
        <script src="{{ URL::asset('libs/node-waves/node-waves.min.js')}}"></script>

        @yield('script')

        <!-- App js -->
        <script src="{{ URL::asset('js/app.min.js')}}"></script>

        @yield('script-bottom')

resources/views/admin/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>
                    document.write(new Date().getFullYear())
                </script> © BNI.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    Design & Develop by BNI Life
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/layouts/head.blade.php
@yield('css')

<!-- App css -->
<link href="{{ URL::asset('/css/bootstrap-dark.min.css')}}" id="bootstrap-dark" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('/css/bootstrap.min.css')}}" id="bootstrap-light" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('/css/app-rtl.min.css')}}" id="app-rtl" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('/css/app-dark.min.css')}}" id="app-dark" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('/css/app.min.css')}}" id="app-light" rel="stylesheet" type="text/css" />


<style>
        #layout-wrapper::before {
                background: #EF5A25 !important;
        }

        #layout-wrapper::after {
                background: none !important;
        }
</style>

resources/views/admin/layouts/master-layouts.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title> @yield('title') | BNI Life</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('layouts.head')
</head>

@yield('body')
@show

<body data-layout="horizontal" data-topbar="dark">
    <!-- Begin page -->
    <div class="container-fluid">
        <div id="layout-wrapper">
            @include('layouts.hor-menu')
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">
                <div class="page-content">
                    @yield('content')
                </div>
                @include('layouts.footer')
            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
        </div>
        <!-- END wrapper -->
    </div>
    <!-- Right Sidebar -->
    @include('layouts.right-sidebar')
    <!-- END Right Sidebar -->

    @include('layouts.footer-script')
</body>

</html>

resources/views/admin/layouts/master-without-nav.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title> @yield('title') | BNI Life</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('admin.layouts.head')
</head>
@yield('body')

@yield('content')

@include('admin.layouts.footer-script')
</body>

</html>

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>@yield('title') | BNI Life</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('admin.layouts.head')
    @yield('style')
</head>

@section('body')
@show

<body data-layout="detached" data-topbar="colored">
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner-chase">
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
            </div>
        </div>
    </div>
    <!-- Begin page -->
    <div class="container-fluid">
        <div id="layout-wrapper">
            @include('admin.layouts.topbar')
            @include('admin.layouts.sidebar')
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">
                <div class="page-content">
                    @yield('content')
                </div>
                <!-- End Page-content -->
                @include('admin.layouts.footer')
            </div>
            <!-- end main content-->
        </div>
        <!-- END layout-wrapper -->
    </div>
    <!-- END container-fluid -->

    <!-- JAVASCRIPT -->
    @include('admin.layouts.footer-script')

    @yield('scripts')
</body>

</html>

resources/views/admin/layouts/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>
                
                {{-- <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Banner</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Kirim E-Polis</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Transaksi</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Nasabah</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Pages</span>
                    </a>
                    <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                        <li><a href="email-inbox.html">Tentang Kami</a></li>
                        <li><a href="email-inbox.html">Layanan</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Promosi</span>
                    </a>
                    <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                        <li><a href="email-inbox.html">Produk</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">FAQ</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Testimoni</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Produk</span>
                    </a>
                    <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                        <li><a href="email-inbox.html">Kategori</a></li>
                        <li><a href="email-inbox.html">Produk</a></li>
                        <li><a href="email-read.html">Plan</a></li>
                    </ul>
                </li> --}}
                <li>
                    <a href="{{ route('admin.perisai-plus') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Perisai Plus</span>
                    </a>
                </li>
                {{-- <li>
                    <a href="{{ route('admin.hubungi-kami') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Hubungi Kami</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.hubungi-kami') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Mitra Kami</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.hubungi-kami') }}">
                        <i class="mdi mdi-view-list"></i>
                        <span href="layouts-horizontal">Video Panduan</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.hubungi-kami') }}">
                        <i class="mdi mdi-settings"></i>
                        <span href="layouts-horizontal">Statistik</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.settings.index') }}">
                        <i class="mdi mdi-settings"></i>
                        <span href="layouts-horizontal">Settings</span>
                    </a>
                </li> --}}

            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/admin/layouts/topbar.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="container-fluid">
            <div class="float-right">

                <div class="dropdown d-inline-block d-lg-none ml-2">
                    <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="mdi mdi-magnify"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0" aria-labelledby="page-header-search-dropdown">

                        <form class="p-3">
                            <div class="form-group m-0">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="dropdown d-none d-lg-inline-block ml-1">
                    <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                        <i class="mdi mdi-fullscreen"></i>
                    </button>
                </div>

                <div class="dropdown d-inline-block">
                    <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-none d-xl-inline-block ml-1">Admin</span>
                        <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-danger" href="{{ route('logout') }}"><i class="bx bx-power-off font-size-16 align-middle mr-1 text-danger"></i> Logout</a>
                    </div>
                </div>

            </div>
            <div>
                <!-- LOGO -->
                <div class="navbar-brand-box">
                    <a href="index" class="logo logo-dark">
                        <span class="logo-sm">
                            <img src="{{ url('images/logo-sm.png') }}" alt="" height="20">
                        </span>
                        <span class="logo-lg">
                            <img src="{{ url('images/logo-dark.png') }}" alt="" height="17">
                        </span>
                    </a>

                    <a href="index" class="logo logo-light">
                        <span class="logo-sm">
                            <img src="{{ url('images/logo-sm.png') }}" alt="" height="20">
                        </span>
                        <span class="logo-lg">
                            <img src="{{ url('images/icons/logo-bni-header.svg') }}" alt="" height="49">
                        </span>
                    </a>
                </div>

                <button type="button" class="btn btn-sm px-3 font-size-16 header-item toggle-btn waves-effect" id="vertical-menu-btn">
                    <i class="fa fa-fw fa-bars"></i>
                </button>
            </div>

        </div>
    </div>
</header>