routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
    // You can also use auth middleware to prevent unauthenticated users
    Route::get('/', 'DashboardController@index');

    Route::group((['prefix' => 'perisai-plus']), function () {
        Route::get('/', 'PerisaiPlusController@index')->name('admin.perisai-plus');
        Route::get('/get-perisai-plus', 'PerisaiPlusController@getPerisaiPlus')->name('admin.perisai-plus.datatables');
    });
    Route::group((['prefix' => 'hubungi-kami']), function () {
        Route::get('/', 'HubungiKamiController@index')->name('admin.hubungi-kami');
        Route::get('/get-hubungi-kami', 'HubungiKamiController@getHubungiKami')->name('admin.hubungi-kami.datatables');
    });

    Route::group((['prefix' => 'about']), function () {
        Route::get('/', 'AboutusController@index')->name('admin.about');
        Route::post('/store/{id}', 'AboutusController@store')->name('admin.about.store');
    });

    Route::group((['prefix' => 'terms']), function () {
        Route::get('/', 'TermsController@index')->name('admin.terms');
        Route::post('/store/{id}', 'TermsController@store')->name('admin.terms.store');
    });

    Route::resource('settings', 'SettingController')->names('admin.settings');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Library\Helpers\BnilifeApi;
use Illuminate\Support\Facades\Cookie;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Frontend'], function () {
  Route::group(['prefix' => 'produk'], function () {
    Route::get('/{slug}', 'ProductController@single_category')->name('produk.single_category');
  });
  Route::group(['prefix' => 'plan'], function () {
    Route::get('/{slug}', 'ProductController@single_product')->name('produk.single_product');
  });
  Route::get('/register', 'RegisterController@index')->name('register-plan');
  Route::get('/perisai-plus', 'PerisaiController@index')->name('front.perisai_plus');
});

Auth::routes(['register' => false]);
Route::get('/404', 'ErrorController@notfound');
Route::get('/500', 'ErrorController@pageerror');
Route::get('/polish', 'PolishController@index');




// hanya untuk test
// Route::post('geturl', 'MidtransController@getUrlPayment');
// Route::get('midtrans', 'MidtransController@index');


Route::get('perisai', 'Api\PerisaiController@index')->name('perisai');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/service', 'HomeController@service')->name('service');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/register/success', 'HomeController@registerSuccess')->name('register-success');
// Route::get('/product', 'HomeController@product');
// Route::get('/packet', 'HomeController@packet');

Route::get('/contact', 'HomeController@contact')->name('contact');

// Route::get('/test-email', function () {
//   $detail = [
//     'view' => 'mail.registration-perisai-plus',
//     'subject' => 'Hello',
//     'title' => 'Title',
//     'body' => 'Test Body',
//   ];
//   SendEmail::dispatch('kurniarocki30@gmail.com', $detail);
// });

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\SettingParameter;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = SettingParameter::all();
        return view('admin.setting.index', compact('settings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $settings = SettingParameter::all();

        foreach ($settings as $key) {
            $value = $request->input($key->SETTING_ID);
            if($key->SETTING_TYPE=='PDF'){
                if($request->hasFile($key->SETTING_ID)){

                }else{
                    continue;
                }
            }
            $setting = SettingParameter::find($key->SETTING_ID);
            $setting->SETTING_VALUE = $value;
            $setting->save();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/setting/index.blade.php
@extends('admin.layouts.master')

@section('title') Setting @endsection

@section('content')

@component('common-components.breadcrumb')
@slot('title') Setting @endslot
@endcomponent

@section('style')

@endsection

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('admin.settings.store')}}" method="POST" enctype="multipart/form-data">
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                @foreach ($settings as $setting)
                                @php
                                $type="text";
                                $value=$setting->SETTING_VALUE;
                                $name=$setting->SETTING_ID;
                                if($setting->SETTING_TYPE=='PDF'){
                                $type="file";
                                $value="";
                                }
                                $input = '<input type="'.$type.'" name="'.$name.'" value="'.$value.'" class="form-control">';
                                @endphp
                                <td>
                                    <label for="">{{$setting->SETTING_DESC}}</label>
                                </td>
                                <td>
                                    {!!$input!!}
                                </td>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12 text-right">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
@endsection